AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  jm-subscribe-api

  Sample SAM Template for jm-subscribe-api
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: nodejs16.x
    Architectures:
        - x86_64
    Environment:
      Variables:
        JM_SUBSCRIBE_TABLE: !Ref Table
        REGION_NAME: !Ref Region
Parameters:
  Table:
    Type: String
    Default: JmSubscribe
  Region:
    Type: String
    Default: us-east-1

Resources:
  JmSubscribeApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,POST'"
        AllowHeaders: "'content-type'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
        AllowCredentials: false

  SubscribeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: handler/
      Handler: subscribe.subscribe
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref JmSubscribe
      
      Events:
        Subscribe:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /jmSubscribe
            Method: post

  JmSubscribe:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        #BillingMode: PAY_PER_REQUEST
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: !Ref Table

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  JmSubscribeApi:
    Description: "API Gateway endpoint URL for Prod stage for Subscribe function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/jmSubscribe/"
  SubscribeFunction:
    Description: "Subscribe Lambda Function ARN"
    Value: !GetAtt SubscribeFunction.Arn
